version: '3.5'

services:

  bitcoind:
    build:
      context: .
      dockerfile: docker/bitcoind.Dockerfile
    ports:
      - "8332:8332"
      - "18444:18444"
    entrypoint: ["./bvaultd","-conf=/bitcoin/bitcoind-regtest.conf"]

  electrumx:
    build:
      context: .
      dockerfile: docker/electrumx.Dockerfile
    ports:
      - "50001:50001"
      - "50002:50002"
      - "50004:50004"
      - "10000:10000"
    volumes:
      - ./:/electrumx/
    environment:
      HOME: /data
      DB_DIRECTORY: /data
      DAEMON_URL: user:pass@bitcoind:8332
      COIN: BitcoinVault
      NET: regtest
      SERVICES: tcp://:50001,ssl://:50002,wss://:50004,rpc://0.0.0.0:10000
    command:
      - sh
      - -c
      - |
        cd /electrumx/
        mkdir data
        python setup.py install
        python electrumx_server
